Fixed $tabularData on overview.php
kint-php/kint pull request #220
Opened 2016-11-03 20:56 UTC by DRSDavidSoft

Apparently, In order for the latest versions of Kint to show 2-d arrays in tabular-view, no columns should have more than 50% empty cells .

2016-11-03 20:57 UTC, DRSDavidSoft commented
Fixes #219.

2017-03-09 19:07 UTC, DRSDavidSoft commented
Is this PR still relevant for Kint 2.0 examples? Or the new plugin replaces this?

2017-03-09 19:11 UTC, jnvsor commented
The new plugin replaces it. It's also more strict than the old behaviour so it'll likely make your issue in #219 worse, though you can mitigate that by writing your own plugin for it.

If you don't find any massive explosive issues with it, mind if I close the PR and issue?

2017-03-09 19:15 UTC, DRSDavidSoft commented
I don't mind at all, but IMO it's more appropriate if you push it to the 1.0 branch for historical versions (some future visitors might still be wanting to use the older version of kint.)

It's just an example script, after all.

2017-03-09 19:19 UTC, jnvsor commented
Ah true, I thought this was tweaking behaviour not an example. Though I do spy a bug right off: The day in the dates will go up to `2013-01-011` now. Lower the condition to 10 or so and it should be fine

2017-03-09 19:54 UTC, DRSDavidSoft commented
You have eagle eyes! I hope you accept this solution, I tried to keep it still readable.

2017-03-09 20:01 UTC, jnvsor requested changes

2017-03-09 20:01 UTC, jnvsor commented on examples/overview.php
> +	$number = str_pad($input, 2, "0", STR_PAD_LEFT);
I spy with my little eye, copy pastey pastey :)

2017-03-09 20:15 UTC, jnvsor commented on examples/overview.php
> +	$number = str_pad($input, 2, "0", STR_PAD_LEFT);
In case you still don't see it: `$i != $input`

2017-03-10 17:48 UTC, DRSDavidSoft commented on examples/overview.php
> +	$number = str_pad($input, 2, "0", STR_PAD_LEFT);
That's actually a misplaced auto completion. That's what happens if I hurry to commit :D

2017-03-10 17:52 UTC, DRSDavidSoft reviewed
Done. Sorry about multiple commits!

2017-03-10 17:53 UTC, DRSDavidSoft commented
Everything good for the PR now?

2017-03-10 17:54 UTC, jnvsor commented
No problem - I'll squash them in the end. Just let me test this quickly

2017-03-10 17:57 UTC, jnvsor approved these changes

2017-03-10 17:58 UTC, jnvsor commented
Squashed as 425c6127b54e47934f36d69519342c94d2d1c911

2017-03-10 17:58 UTC, closed without merging