Vim navigation keys (& keyboard error fix)
kint-php/kint pull request #225
Opened 2016-12-21 08:37 UTC by neitanod

Use "hjkl" as arrow keys (for Vim fanatics)
Use "j" as an alternative to enable keyboard navigation (makes sense for Vimmers too).
Fixed error when trying to expand "Called from..." using keyboard navigation

2016-12-21 14:36 UTC, raveren commented
Hello and thank you for the support - and the work you put into your two PRs!!! 

The bugfix is but a workaround unfortunately, the perfect case scenario would be to make the shortcut actually expand the footer, however I haven't gotten around to that - still it's better than previously, so it's acceptable as a change. I'll add the few other nitpicks in the code review :)

2016-12-21 14:48 UTC, raveren requested changes
sorry for being a bit anal :)

2016-12-21 14:48 UTC, raveren commented on view/base.js
> +		} else if ( keyCode === 39 || keyCode === 37 || keyCode === 76 || keyCode === 72 ) { // ARROW LEFT/RIGHT : respectively hides/shows and traverses
this line is too long, I think 120 is a sane maximum

2016-12-21 14:48 UTC, raveren commented on view/base.js
> +		if ( keyCode === 68 || (keyCode === 74 && j_toggles) ) { // 'd' or 'j' : toggles navigation on/off
So 'j' toggles navigation as well as navigate - but how do you get out of kint navigation mode and just want to scroll the page with arrow keys? 'd'? That's a bit counter-intuitive, don't you think? I'm not a VIM buff, so what's your oppinion?

2016-12-21 14:48 UTC, raveren commented on view/base.js
> +			} else if ( keyCode === 38 || keyCode === 75 ) { // ARROW UP : moves up
This as well as other places should reflect your change in the comments, cause keyCode 75 is highly unreadable. Please observe the line limit as well.

2016-12-21 14:48 UTC, raveren commented on view/base.js
> +}
This is a nitpick, but changes to spacing mess up git blame, it's too easy to avoid it here to not to :)

2016-12-21 14:48 UTC, raveren commented on view/base.js
> +	var j_toggles = 1;
Nitpick: j_toggles is an undescriptive variable name (I know, the file is not that readable already), but it a) indicates it's a counter just by it not having a boolean value b) `navStartedByJ` or something similar would adhere to camelCase convention of the whole file and describe the purpose of the variable better

2016-12-21 15:45 UTC, neitanod commented
The fix works fine in my machine.  Give it a try  :)
It stops the "do ... while" from diverting to other element when current one is "footer", so it expands both on click and on key press (I tried <right_arrow>, <enter> and <L>).

2016-12-21 15:47 UTC, neitanod commented on view/base.js
> +}
This change to spacing was accidental (initially) and I was trying to get it back to how you got it, but failed, apparently.  :P

2016-12-21 15:50 UTC, neitanod commented on view/base.js
> +		} else if ( keyCode === 39 || keyCode === 37 || keyCode === 76 || keyCode === 72 ) { // ARROW LEFT/RIGHT : respectively hides/shows and traverses
I did split it originally, and that's when I realized that you use tabs for indentation.  I didn't really know how to indent such a half line correctly.
I'll give it a try, and you please correct me if I get it wrong.

2016-12-21 16:02 UTC, neitanod commented on view/base.js
> +		if ( keyCode === 68 || (keyCode === 74 && j_toggles) ) { // 'd' or 'j' : toggles navigation on/off
The ESC key would be the "Vim way" to get out of navigation mode, I think.

2016-12-21 16:40 UTC, neitanod commented on view/base.js
> +		if ( keyCode === 68 || (keyCode === 74 && j_toggles) ) { // 'd' or 'j' : toggles navigation on/off
The boolean just says if keyboard navigation is active already or not, so I'm about to push it with the name _keyboardNavigationIsActive_

2016-12-21 16:55 UTC, jnvsor commented
> make the shortcut actually expand the footer, however I haven't gotten around to that

That's working in 2.x. I'll be pushing my latest commits to jnvsor and Kint-PHP soon

2017-03-09 17:12 UTC, jnvsor commented
I added the hjkl navigation to kint in 2.x-dev, and fixed the error before then. I'm not convinved j to activate in addition to d is worth the effort. Could you try it and see how it feels?

2017-04-08 20:16 UTC, closed without merging