Cleaned up warnings and provided some error checking in build.php
kint-php/kint pull request #299
Opened 2019-01-25 21:16 UTC by deanhouseholder

Added a try/catch block to minimize PHP fatal error output while retaining the message.

2019-01-25 21:29 UTC, jnvsor requested changes
> I'm going to cancel and submit a new one.

FYI: You can force push to your branch to automatically update the PR, no need to make a new one

2019-01-25 21:29 UTC, jnvsor commented on build.php
> +}
This try catch is redundant, since the exception will result in a fatal error anyway (And a real one, with the proper exit code, print to stderr, etc)

2019-01-25 21:29 UTC, jnvsor commented on build.php
> +echo 'Your kint.phar has been built successfully and is located in the "build" directory.';
Since there's no output there's a future possibility for us to pipe the script to a file instead of writing directly, I think we should just leave stdout empty for now

2019-03-21 11:19 UTC, raveren commented
Is this maybe why our whole build is broken for weeks :DD @jnvsor I don't think we should keep this open, @deanhouseholder thanks for the effort, and sorry we couldn't make use of the code, but people like you is who inspire us to build things like this.

2019-03-21 11:19 UTC, closed without merging

2019-03-21 17:08 UTC, jnvsor commented
@raveren No, the build isn't broken. @deanhouseholder I'd like to reopen this, but if you don't feel like finishing it up I'll leave it closed.

2019-03-21 19:14 UTC, deanhouseholder commented
I can't understand why you prefer ugly errors to clean ones. Haha


On Thu, Mar 21, 2019 at 11:08 AM Jonathan Vollebregt <
notifications@github.com> wrote:

> @raveren <https://github.com/raveren> No, the build isn't broken.
> @deanhouseholder <https://github.com/deanhouseholder> I'd like to reopen
> this, but if you don't feel like finishing it up I'll leave it closed.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kint-php/kint/pull/299#issuecomment-475319808>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAr0EQpe8qd1HA1STgpRv6u4XXAFJlxWks5vY7yRgaJpZM4aTq4N>
> .
>

2019-03-21 20:43 UTC, jnvsor commented
This gets a bit unixy as far as technicals go, but programs with text input/output generally have 3 streams: stdin (input) stdout (output) and stderr (error)

Why do you have different streams for output and error? Because it's common to connect programs up to eachother. For instance you could pipe a php script's output to another one like so:

```bash
php script.php | php script2.php
```

If you do it like this, only stdout (The output) is piped to script2, and stderr ends up in the terminal. Apache modphp typically sends both stdout and stderr to the browser, so it doesn't matter there.

The second reason is that programs return a number when they end indicating success or failure. A 0 is success and anything else indicates a variety of failures.

```bash
php script.php && php script2.php
```

In this example script2 will only run if script1 succeeded, which it knows by the exit code. A proper fatal error returns a non-0 exit code, which is also used by CI to tell if things succeeded.

In other words by manually exiting the script *exceptions in the build won't be caught by CI* which is a very bad thing.

Long story short: Smarter people than us thought up these systems and they work very well. No touchy :)